---
name: "✅ Lychee"

on:
  repository_dispatch:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "00 18 * * *"
  push:
    branches: [main]
    paths:
      - "public/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: "📤 Restore cache"
        uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: "📊 Lychee Link Checker"
        id: lychee
        uses: lycheeverse/lychee-action@ef8c8f32c278e9eed290c6e6c96748f16b6cd335
        with:
          args: --config $CONFIG_FILE --base . --verbose --no-progress './public/arf.json' 
          format: markdown
          output: ./docs/LINKS_REPORT.md
          fail: false
          jobSummary: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: ${{ github.workspace }}/.github/lychee.toml

      - name: "🔖 Create Issue From File"
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # v4
        with:
          title: Link Checker Report
          content-filepath: ./docs/LINKS_REPORT.md
          issue-number: 49
          labels: report, automated issue
