---
name: ⭕ Trunk [check]
on:
  push:
    branches: [main]
    tags: [v*.*.*]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: ✨ Trunk Check
        uses: trunk-io/trunk-action@76fcbaff0ca53cae6547c50076a8c477d36cf54a
