---
name: ⭕ Trunk [check]
on:
  push:
    branches: [main]
    tags: [v*.*.*]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v4
      - name: ✨ Trunk Check
        uses: trunk-io/trunk-action@a5258f2190b211fa12bea84eb9258919ebc43b96
